# Generated by Django 4.1.7 on 2023-05-07 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='Projet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.projet'),
        ),
    ]
