# Generated by Django 4.1.7 on 2023-05-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0005_projet_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
