# Generated by Django 4.1.7 on 2023-05-18 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0009_tache'),
    ]

    operations = [
        migrations.CreateModel(
            name='demande_projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approvee', models.BooleanField(default=False)),
                ('refuse', models.BooleanField(default=False)),
                ('Personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.personnel')),
                ('Projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.projet')),
            ],
        ),
    ]
