# Generated by Django 4.1.7 on 2023-05-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0010_demande_projet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tache',
            name='statut',
        ),
        migrations.AddField(
            model_name='tache',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
