# Generated by Django 4.1.7 on 2023-05-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0011_remove_tache_statut_tache_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
