# Generated by Django 4.1.7 on 2023-05-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0012_tache_date_fin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tache',
            old_name='date_fin',
            new_name='date_depot',
        ),
    ]
