# Generated by Django 4.1.7 on 2023-05-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0013_rename_date_fin_tache_date_depot'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='pourcentage',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
