# Generated by Django 4.1.7 on 2023-05-20 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0016_blog_img_blog_texte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='utilusateur',
        ),
    ]
