# Generated by Django 4.1.7 on 2023-05-20 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0017_rename_user_blog_utilusateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='utilusateur',
            new_name='utilisateur',
        ),
    ]
