# Generated by Django 4.1.7 on 2023-05-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0018_rename_utilusateur_blog_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='utilisateur',
            field=models.CharField(max_length=100),
        ),
    ]
