# Generated by Django 4.1.7 on 2023-05-20 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0020_remove_blog_utilisateur_blog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='user',
            new_name='utilisateur',
        ),
    ]
